### ISSUE TITLE
怎么发送组合键命令，还有怎么发送Backspace命令

### ISSUE THREAD

**Issue by 362228416** [shaqian/react-native-ssh-sftp#2]
我在用这个库做一个类似shell的功能，实时输入没有问题，但是没有删除，组合按键 也不知道 怎么做，有做过吗？

**Comment by shaqian** [comment]
xterm里删除的键码值是8，组合键可以参考下xterm.js的实现：
https://github.com/xtermjs/xterm.js/blob/master/src/core/input/Keyboard.ts
https://github.com/xtermjs/xterm.js/blob/master/src/core/input/Keyboard.test.ts
