### ISSUE TITLE
NMSSHSession init error

### ISSUE THREAD

**Issue by assertchris** [shaqian/react-native-ssh-sftp#3]
Hey. Thanks for putting this library together. 

Earlier, I tried to install it, using the Pod instructions; and encountered an error. It was on the line:

```objc
_session = [[NMSSHSession alloc] init];
```

It seems the most recent version of NMSSH doesn't allow the init function to be called. I got around this error by downgrading to the version of NMSSH I saw the example was using. I'm not too familiar with how Podfiles work, but I was wondering if there was a way to set an upper limit for the version of a pod.

If it's possible, I'm happy to submit a PR with the change.

**Comment by shaqian** [comment]
Hi Chris,
Thank you for reporting the issue. I will take a look within this week.

**Comment by Kunalpaul12** [comment]
Use this version of NMSSH in pod
pod 'NMSSH', '2.2.8'

**Comment by shaqian** [comment]
Thanks. I have updated the docs to use fixed version of NMSSH.

**Comment by shaqian** [comment]
Temporarily archiving the thread. Feel free to reopen if you still have the issue.
