### ISSUE TITLE
com.jcraft.jsch.jschexception: auth fail

### ISSUE THREAD

**Issue by vancuf** [shaqian/react-native-ssh-sftp#4]
I'm getting a com.jcraft.jsch.jschexception: auth fail error when connecting to the server, using node.js SSH2 server modules

**Comment by shaqian** [comment]
Sorry for the late response. Are you still having the issue? What is the authentication method used?

**Comment by shaqian** [comment]
Temporarily archiving the thread. Feel free to reopen if you still have the issue.
