### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by shihabawal** [shaqian/react-native-ssh-sftp#5]
I am on Android version 9 on S8+. I cloned the rep and ran it on my device but the app keeps crashing. 

I have noticed this first on my application where trying to run any functions after initialization of `SSHClient` keeps crashing the app. Thinking I have done something wrong I tried the example but that also keeps crashing. 

Tried debugging with the remote debugger but no luck. Please help. Thanks

**Comment by shaqian** [comment]
Hi,

Have you tried launching the app in Android Studio? What error/exception do you get?

Thanks,
Qian

**Comment by shaqian** [comment]
Temporarily archiving the thread. Feel free to reopen if you still have the issue.
