### ISSUE TITLE
Error: I try to build for release with this packages

### ISSUE THREAD

**Issue by Vaxela** [shaqian/react-native-ssh-sftp#6]
> Task :react-native-ssh-sftp:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ssh-sftp:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:7: error: resource android:attr/colorError not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2711: error: resource android:attr/fontStyle not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2712: error: resource android:attr/font not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2713: error: resource android:attr/fontWeight not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2715: error: resource android:attr/ttcIndex not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2796: error: resource android:attr/startX not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2799: error: resource android:attr/startY not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2802: error: resource android:attr/endX not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2805: error: resource android:attr/endY not found.
  D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\node_modules\react-native-ssh-sftp\android\build\intermediates\res\merged\release\values\values.xml:2813: error: resource android:attr/offset not found.
  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 52s
237 actionable tasks: 3 executed, 234 up-to-date
PS D:\vaxel\Documents\Feedbook\test\feedbook-mobile-react\android>

**Comment by shaqian** [comment]
Looks like the error is same as the thread below. Please try the solutions in the answers.
https://stackoverflow.com/questions/52613089/getting-verifyreleaseresources-error-after-upgrading-react-native

Thanks,
Qian

**Comment by Vaxela** [comment]
Yes its working i just put compiled version 28 in subproject ect :D
